stages:
  train:
    cmd: python train.py
    deps:
    - data/MNIST
    - train.py
    params:
    - params.yaml:
    outs:
    - model.pt:
        checkpoint: true
    metrics:
      - training_metrics.json:
          persist: true
          cache: false
    plots:
    - training_metrics
    - misclassified.jpg
    - predictions.json:
        template: confusion
        x: actual
        y: predicted
