stages:
  train:
    cmd: python train.py
    deps:
    - data/MNIST
    - train.py
    params:
    - seed
    - lr
    - weight_decay
    - otherparams.yaml:
        - test
    - nested/otherparams.yaml:
        - test
    outs:
    - model.pt:
        checkpoint: true
    plots:
    - predictions.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
    live:
      logs:
        summary: true
        html: true
