stages:
  train:
    cmd: python train.py
    deps:
    - data/MNIST
    - train.py
    params:
    - params.yaml:
    outs:
    - model.pt:
        checkpoint: true
    metrics:
      - training_metrics.json:
          cache: false
          persist: true
    plots:
    - training_metrics:
        cache: false
    - missclassified.jpg:
        cache: false
    - predictions.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
