seed: 473987
lr: 0.001
weight_decay: 0
another_metric:
  kek: 123456789
  deeper:
    is_this_a_bug: 1337
    how_deep_does_it_go:
      wow_hello_world: 1231232
  deeper2:
    this_is_fine_everything_is_fine: 123423
    bfhwew:
      oiwerhyuwef: 123
jebhwfvegw:
  jfebwfh: 2342
  fbwev: 2382
  kjfwfhehihui:
    jweir:
      oiwhrew: 232